name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  cloud-build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Taskfile
        uses: go-task/setup-task@v1

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/fami-2026
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Images
        env:
          SERVER_ADDR: ${{ vars.SERVER_ADDR }}
        run: task server:image

      - name: Publish Images
        run: task server:publish

  cloud-deploy:
    needs: cloud-build
    runs-on: nstu
    environment:
      name: cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Taskfile
        uses: go-task/setup-task@v1

      - name: Deploy
        run: task server:deploy
        env:
          ORIGIN: ${{ vars.ORIGIN }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}

  pages-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fami-2026/vge.dev:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        run: task client:ci
      
      - name: Build Static
        run: task client:ci:build
        env:
          SERVER_ADDR: ${{ vars.SERVER_ADDR }}
          BASE: /vector-graphic-editor/

      - name: Upload
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist/

  pages-deploy:
    needs: pages-build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
